CREATE TABLE [dbo].[Properties] (
    [Portfolio Name]                                          NVARCHAR (MAX) NULL,
    [Property ID - External]                                  NVARCHAR (MAX) NULL,
    [Property ID - Internal]                                  NVARCHAR (MAX) NULL,
    [Property Name]                                           NVARCHAR (MAX) NULL,
    [Asset Class ]                                            NVARCHAR (MAX) NULL,
    [Subasset Class ]                                         NVARCHAR (MAX) NULL,
    [Submarket]                                               NVARCHAR (MAX) NULL,
    [Year of Construction]                                    BIGINT         NULL,
    [Year of Modernisation ]                                  BIGINT         NULL,
    [Main Tenant]                                             NVARCHAR (MAX) NULL,
    [Sector (of Main Tenant)]                                 NVARCHAR (MAX) NULL,
    [Total Rental Space (sqm)]                                BIGINT         NULL,
    [Vancancy Rate ]                                          BIGINT         NULL,
    [Date of Condition]                                       DATE           NULL,
    [WALT]                                                    BIGINT         NULL,
    [Picture ]                                                NVARCHAR (MAX) NULL,
    [Utilisation]                                             NVARCHAR (MAX) NULL,
    [Parking Lots]                                            BIGINT         NULL,
    [Number of Units]                                         BIGINT         NULL,
    [Office Share]                                            FLOAT (53)     NULL,
    [Retail Share]                                            FLOAT (53)     NULL,
    [Residential Share]                                       FLOAT (53)     NULL,
    [Hotel Share]                                             FLOAT (53)     NULL,
    [Leisure Share]                                           FLOAT (53)     NULL,
    [Industrial Share ]                                       FLOAT (53)     NULL,
    [Logistics Share]                                         FLOAT (53)     NULL,
    [Gastronomy Share]                                        FLOAT (53)     NULL,
    [Parking Share]                                           FLOAT (53)     NULL,
    [Health Care Share]                                       FLOAT (53)     NULL,
    [Commercial Park Share]                                   FLOAT (53)     NULL,
    [Mixed-Use Share]                                         FLOAT (53)     NULL,
    [Serviced Apartments Share]                               FLOAT (53)     NULL,
    [Others Share]                                            FLOAT (53)     NULL,
    [Development Site Share]                                  FLOAT (53)     NULL,
    [EPC Rating]                                              NVARCHAR (MAX) NULL,
    [Energy Consumption (kwH/sqm/ p.a )]                      BIGINT         NULL,
    [Building Type]                                           NVARCHAR (MAX) NULL,
    [Divisibility]                                            BIGINT         NULL,
    [Federal State]                                           NVARCHAR (MAX) NULL,
    [Region]                                                  NVARCHAR (MAX) NULL,
    [Postal Code]                                             BIGINT         NULL,
    [City]                                                    NVARCHAR (MAX) NULL,
    [Street]                                                  NVARCHAR (MAX) NULL,
    [Number]                                                  NVARCHAR (MAX) NULL,
    [Latitude]                                                FLOAT (53)     NULL,
    [Longitude]                                               FLOAT (53)     NULL,
    [Compare Address ( For HQ )]                              NVARCHAR (MAX) NULL,
    [Distance HQ]                                             FLOAT (53)     NULL,
    [Distance Main Station ]                                  FLOAT (53)     NULL,
    [Distance Next Public Transit]                            FLOAT (53)     NULL,
    [Distance City Center]                                    FLOAT (53)     NULL,
    [Distance Airport]                                        FLOAT (53)     NULL,
    [Distance High Way]                                       FLOAT (53)     NULL,
    [Any Other Important Distance]                            BIGINT         NULL,
    [Next Public Transit]                                     NVARCHAR (MAX) NULL,
    [Main Tenant Income ]                                     BIGINT         NULL,
    [Total Current Rent ( EUR p.a )]                          BIGINT         NULL,
    [Average Current Rent (EUR / sqm / p.m )]                 FLOAT (53)     NULL,
    [Stabilized Total Rent (EUR / p.a )]                      BIGINT         NULL,
    [Total Current Market Rent  (EUR / p.a )]                 BIGINT         NULL,
    [Average Current Market Rent (EUR / sqm / per month )]    BIGINT         NULL,
    [Total Share of Income of Main Asset Class ( EUR / p.a )] BIGINT         NULL,
    [Population Development Last 5 Years]                     FLOAT (53)     NULL,
    [Population Forecast 2035]                                FLOAT (53)     NULL,
    [Population Information Range]                            NVARCHAR (MAX) NULL,
    [Purchasing Power]                                        FLOAT (53)     NULL,
    [Centrality]                                              BIGINT         NULL,
    [Population Amount]                                       BIGINT         NULL,
    [Unemployment]                                            FLOAT (53)     NULL
);


GO

